# 

In [2]:
import numpy as np

In [3]:
L = [1, 2, 3]

In [4]:
A = np.array(L)

In [5]:
L

[1, 2, 3]

In [6]:
A

array([1, 2, 3])

In [7]:
for e in L:
    print(e)

1
2
3


In [9]:
for e in A:
    print(e)

1
2
3


In [10]:
L.append(4)
L

[1, 2, 3, 4]

Don't try to resize numpy arrays in place

In [17]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [18]:
A + A

array([2, 4, 6])

In [21]:
L2 = []
for e in L:
    L2.append(e + 3)
L2

[4, 5, 6, 7]

In [22]:
A + 3

array([4, 5, 6])

In [24]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [25]:
A**2

array([1, 4, 9])

In [26]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

Dot Product:

In [27]:
a = np.array([1, 2])
b = np.array([3, 4])

In [28]:
dot = 0
for e, f in zip(a, b):
    dot += e * f
dot

11

In [29]:
a.dot(b)

11

In [30]:
np.dot(a, b)

11

In [31]:
a * b

array([3, 8])

In [32]:
np.sum(a * b)

11

In [33]:
(a * b).sum()

11

In [34]:
a @ b

11

In [41]:
a_mag = np.sqrt(a @ a)
a_mag

2.23606797749979

In [42]:
b_mag = np.sqrt(b @ b)
b_mag

5.0

In [43]:
cos_ab = (a @ b)/(a_mag * b_mag)
cos_ab

0.9838699100999074

In [44]:
np.linalg.norm(a)

2.23606797749979

In [45]:
theta = np.arccos(cos_ab)

In [46]:
theta

0.17985349979247847