# 

In [2]:
import numpy as np

In [3]:
L = [1, 2, 3]

In [4]:
A = np.array(L)

In [5]:
L

[1, 2, 3]

In [6]:
A

array([1, 2, 3])

In [7]:
for e in L:
    print(e)

1
2
3


In [8]:
for e in A:
    print(e)

1
2
3


In [9]:
L.append(4)
L

[1, 2, 3, 4]

Don't try to resize numpy arrays in place

In [10]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [11]:
A + A

array([2, 4, 6])

In [12]:
L2 = []
for e in L:
    L2.append(e + 3)
L2

[4, 5, 6, 7]

In [13]:
A + 3

array([4, 5, 6])

In [14]:
L**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [15]:
A**2

array([1, 4, 9])

In [16]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

Dot Product:

In [17]:
a = np.array([1, 2])
b = np.array([3, 4])

In [18]:
dot = 0
for e, f in zip(a, b):
    dot += e * f
dot

11

In [19]:
a.dot(b)

11

In [20]:
np.dot(a, b)

11

In [21]:
a * b

array([3, 8])

In [22]:
np.sum(a * b)

11

In [23]:
(a * b).sum()

11

In [24]:
a @ b

11

In [25]:
a_mag = np.sqrt(a @ a)
a_mag

2.23606797749979

In [26]:
b_mag = np.sqrt(b @ b)
b_mag

5.0

In [27]:
cos_ab = (a @ b)/(a_mag * b_mag)
cos_ab

0.9838699100999074

In [28]:
np.linalg.norm(a)

2.23606797749979

In [29]:
theta = np.arccos(cos_ab)

In [30]:
theta

0.17985349979247847

Solving Linear Systems

In [32]:
A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200, 5050])

In [33]:
np.linalg.solve(A, b)

array([1500.,  700.])

In [34]:
np.linalg.inv(A).dot(b)

array([1500.,  700.])

Generating Data

In [36]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [37]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.ones((2, 3)) * 10

array([[10., 10., 10.],
       [10., 10., 10.]])

In [39]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [40]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [44]:
np.random.random()

0.24665767128855964

In [45]:
np.random.random((2, 3))

array([[0.03559986, 0.39868754, 0.47144005],
       [0.50286547, 0.65733533, 0.40320124]])

In [47]:
np.random.randn(2, 3)

array([[ 0.11022218, -0.4618017 , -0.24912557],
       [ 0.52260202, -1.272154  , -0.03263228]])

In [48]:
R = np.random.randn(10_000)

In [49]:
R.mean()

-0.002582228359225114

In [50]:
R.std()

0.9893834111699213

In [51]:
R.var()

0.9788795342982296

In [53]:
R.var()**(1/2)

0.9893834111699213

In [54]:
R = np.random.randn(10000, 3)

In [55]:
R.mean(axis=0) # mean of each column

array([0.00271908, 0.01028754, 0.00048931])

In [56]:
R.mean(axis=1) # mean of each row

array([-0.18588503,  0.16324092, -0.08126325, ...,  0.6525196 ,
        0.76491203,  0.41010288])

In [57]:
np.cov(R)

array([[ 1.3598308 ,  0.30123897,  0.33662763, ..., -0.07184325,
        -0.79869758, -0.06087342],
       [ 0.30123897,  2.3595045 , -1.70141979, ..., -0.78654328,
        -0.71470744, -0.49754094],
       [ 0.33662763, -1.70141979,  1.45902407, ...,  0.57914721,
         0.21884416,  0.35988262],
       ...,
       [-0.07184325, -0.78654328,  0.57914721, ...,  0.26281297,
         0.22294963,  0.16591305],
       [-0.79869758, -0.71470744,  0.21884416, ...,  0.22294963,
         0.59525174,  0.14929037],
       [-0.06087342, -0.49754094,  0.35988262, ...,  0.16591305,
         0.14929037,  0.10492013]])

In [59]:
np.cov(R.T)

array([[ 0.99834777,  0.00354294, -0.00532419],
       [ 0.00354294,  0.98096246, -0.00471279],
       [-0.00532419, -0.00471279,  1.02662613]])

In [60]:
np.cov(R, rowvar=False)

array([[ 0.99834777,  0.00354294, -0.00532419],
       [ 0.00354294,  0.98096246, -0.00471279],
       [-0.00532419, -0.00471279,  1.02662613]])

In [61]:
np.random.randint(0, 10,  size=(3, 3))

array([[1, 2, 1],
       [2, 0, 9],
       [1, 8, 4]])

In [64]:
np.random.choice(["dog", "cat", "duck"], (3, 3))

array([['cat', 'dog', 'cat'],
       ['dog', 'dog', 'cat'],
       ['cat', 'duck', 'duck']], dtype='<U4')

In [65]:
a

array([1, 2])

In [67]:
b

array([2200, 5050])

# Add some Text